name: "Send notification"

on:
  workflow_call:
    inputs:
      CVE_CRITICAL:
        required: true
        type: string
      CVE_HIGH:
        required: true
        type: string
      CVE_MEDIUM:
        required: true
        type: string
    secrets:
      CVE_SCAN_SLACK_WEBHOOK:
        required: true

jobs:
  Notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    environment: cstar-d-weu-rtp
    steps:
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02dz #v2.0.0
        with:
          webhook: ${{ secrets.CVE_SCAN_SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "[ ${{ github.event.repository.name }} ]"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: " `CRITICAL` : *${{ inputs.CVE_CRITICAL }}*\n\n`HIGH` : *${{ inputs.CVE_HIGH }}*\n\n`MEDIUM` : *${{ inputs.CVE_MEDIUM }}*\n\n<https://github.com/${{ github.repository }}/security/code-scanning |See details on GitHub>"
